accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    # path(route="/", view=include('allauth.urls')),
    path(route="signup", view=views.signup, name="signup"),
    path(route="signin", view=views.signin, name="signin"),
    path(route="signout", view=views.signout, name="signout"),
]

blog/urls.py
from . import views
from django.urls import path
from .import views

app_name = 'blog'

urlpatterns = [
    path(route='', view=views.blogs, name='blogs'),
    path(route='blogs/', view=views.blogDetails, name='blog_details'),
    path(route='search/', view=views.search, name='search'), 
]

liame/urls.py
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path(route='accounts/', view=include('accounts.urls')),
    path(route='blog/', view=include('blog.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text="Required. Enter a valid email address.")

    class Meta:
        model = User  # Replace 'User' with your custom User model if you have one
        fields = ('username', 'email', 'password1', 'password2')

accounts/views.py
from django.db.models import Q
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import login
from django.contrib.auth import logout
# from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm
from django.contrib.auth.forms import AuthenticationForm

# Create your views here.


def signin(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request=request, user=user)
            if 'next' in request.POST:
                return redirect(to=request.POST.get('next'))
            else:
                return redirect(to='/')
        else:
            error = 'Please enter correct username and password. Click "Lets sign you up" if you dont have an account.'
            template_name = 'accounts/signin.html'
            context = {'form': AuthenticationForm(), 'error': error}
            return render(request, template_name=template_name, context=context)
    else:
        template_name = 'accounts/signin.html'
        context = {'form': AuthenticationForm()}
    return render(request, template_name=template_name, context=context)



def signout(request):
    logout(request=request)
    return redirect(to='/')


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            # login user
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('/')
        else:
            # Customize error messages
            error = form.errors
            template_name = 'accounts/signup.html'
            context = {'form': CustomUserCreationForm(), 'error': error}
            return render(request, template_name=template_name, context=context)
    else:
        template_name = 'accounts/signup.html'
        context = {'form': CustomUserCreationForm()}
    return render(request=request, template_name=template_name, context=context)

accounts/templates/accounts/signin.html
<!-- Signin Page -->
{% extends 'components/base.html' %}
<!--Page Title -->
{% block title %}
<title>SignIn</title>
{% endblock title%}
<!-- Page Content -->
{% block content %}
<!-- Load Social Account -->
{% load socialaccount %}
<style>
  input {
    padding: 0.25em;
    border-radius: 0.25em;
    border: 1.5px solid lightgray;
  }
</style>
<main id="main">
  <!-- ======= Breadcrumbs ======= -->
  <section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
      <div class="d-flex justify-content-between align-items-center">
        <h2 class="p-2">Welcome back, login</h2>
      </div>
    </div>
  </section>
  <!-- End Breadcrumbs -->

  <!-- ======= Portfolio Details Section ======= -->
  <section id="portfolio-details" class="portfolio-details">
    <div class="container">
      <div class="d-flex flex-column align-items-center">
        <div>
          <a
            href="{% provider_login_url 'google' %}?next=/"
            class="w-100 btn mb-2"
            style="background-color: #6610f2; color: #fff"
          >
            Login with <i class="bi bi-google"></i>oogle</a
          >
        </div>
        <h4>Or</h4>
        <form
          action="{% url 'accounts:signin'%}"
          method="POST"
          class="login rounded d-flex flex-column shadow p-5"
        >
          <!-- Show Error Message -->
          {% if error %}
          <div class="error p-3 rounded mb-2" style="background: orange">
            {{error}}
          </div>
          {% endif %}
          <!-- End Error Message -->
          {% csrf_token %} {{form}} {% if request.GET.next %}
          <input type="hidden" name="next" value="{{ request.GET.next }}" />
          {% endif %}
          <div class="checkbox mb-3">
            <label>
              <input type="checkbox" value="remember-me" /> Remember me
            </label>
          </div>
          <button
            class="w-100 btn"
            style="background-color: #6610f2; color: #fff"
            type="submit"
          >
            Let me in
          </button>
        </form>
        <div class="d-flex text-center p-3">
          <p>Don't have account?</p>
          <a href="{% url 'accounts:signup'%}"> Let's sign you up</a>
        </div>
      </div>
    </div>
  </section>
  <!-- End Portfolio Details Section -->
</main>
<!-- End #main -->

<!-- JavaScript -->
<script>
  header = document.querySelector("#header");
  header.style.background = "rgba(24, 6, 185, 0.8)";
  document.querySelector(".helptext").style.display = "none";
</script>

{% endblock content %}

accounts/templates/accounts/signup.html
<!-- Signin Page -->
{% extends 'components/base.html' %}
<!--Page Title -->
{% block title %}
<title>SignUp</title>
{% endblock title%}
<!-- Page Content -->
{% block content %}
<!-- Load Social Account -->
{% load socialaccount %}
<style>
  input {
    padding: 0.25em;
    border-radius: 0.25em;
    border: 1.5px solid lightgray;
  }
</style>
<main id="main">
  <!-- ======= Breadcrumbs ======= -->
  <section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
      <div class="d-flex justify-content-between align-items-center">
        <h2 class="p-2">Welcome, signup</h2>
      </div>
    </div>
  </section>
  <!-- End Breadcrumbs -->

  <!-- ======= Portfolio Details Section ======= -->
  <section id="portfolio-details" class="portfolio-details">
    <div class="container">
      <div class="d-flex flex-column align-items-center">
        <div>
          <a
            href="{% provider_login_url 'google' %}?next=/"
            class="w-100 btn mb-2"
            style="background-color: #6610f2; color: #fff"
            >Signup with <i class="bi bi-google"></i>oogle</a
          >
        </div>
        <h4>Or</h4>
        <form
          action="{% url 'accounts:signup'%}"
          method="POST"
          class="login rounded d-flex flex-column shadow p-5"
        >
          <!-- Show Error Message -->
          {% if error %}
          <div class="error p-3 rounded mb-2" style="background: orange">
            {{error}}
          </div>
          {% endif %}
          <!-- End Error Message -->
          {% csrf_token %} {{form}} {% if request.GET.next %}
          <input type="hidden" name="next" value="{{ request.GET.next }}" />
          {% endif %}
          <div class="checkbox mb-3">
            <label>
              <input type="checkbox" value="remember-me" /> Remember me
            </label>
          </div>
          <button
            class="w-100 btn"
            style="background-color: #6610f2; color: #fff"
            type="submit"
          >
            Sign me up
          </button>
        </form>
        <div class="d-flex text-center p-3">
          <p>Don't have account?</p>
          <a href="{% url 'accounts:signin'%}"> Let's sign you in</a>
        </div>
      </div>
    </div>
  </section>
  <!-- End Portfolio Details Section -->
</main>
<!-- End #main -->

<!-- JavaScript -->
<script>
  header = document.querySelector("#header");
  header.style.background = "rgba(24, 6, 185, 0.8)";
  help_texts = document.querySelectorAll(".helptext");
  help_texts.forEach((help_text) => {
    help_text.style.display = "none";
  });
</script>

{% endblock content %}