blog/urls.py
from . import views
from django.urls import path
from .import views

app_name = 'blog'

urlpatterns = [
    path(route='', view=views.blogs, name='blogs'),
    path(route='blogs/', view=views.blogDetails, name='blog_details'),
    path(route='search/', view=views.search, name='search'), 
]

liame/urls.py
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path(route='accounts/', view=include('accounts.urls')),
    path(route='blog/', view=include('blog.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class BlogPage(models.Model):
    image = models.ImageField(upload_to = 'blog/images', default='blog.jpg')
    highlight = models.CharField(max_length=122, default='Welcome to our Blog')
    description = models.CharField(max_length=122, default='Welcome to our Blog')

    def __str__(self):
        return self.highlight

class Author(models.Model):
    name = models.CharField(max_length=122, default='dataidea')
    image = models.ImageField(upload_to = 'blog/images', default='profile.jpg')
    email = models.CharField(max_length=122, default='datasideaofficial@gmail.com')
    profile = models.TextField(default='No profile provided')

    def __str__(self):
        return self.name
   
class BlogCategory(models.Model):
    name = models.CharField(max_length=122, default='New category')
    description = models.CharField(max_length=122, default='New category description')
    color = models.CharField(max_length=122, default='purple')

    def __str__(self):
        return self.name
    
    
class Blog(models.Model):
    slug = models.CharField(max_length=122, default='New Blog Slug')
    title = models.CharField(max_length=122)
    author = models.ForeignKey(to=Author, on_delete=models.CASCADE, default=1)
    category = models.ForeignKey(to=BlogCategory, on_delete=models.CASCADE, default=1)
    brief = models.TextField(default='')
    image = models.ImageField(upload_to = 'blog/images')
    date_featured = models.DateField(auto_now_add=True, null=True, blank=True)
    content_markdown = models.TextField(default='')

    def __str__(self):
        return self.title

blog/views.py
import markdown
from . models import Blog
from . models import BlogPage
from django.db.models import Q
from django.shortcuts import render
from django.core.paginator import Paginator
from index.models import (CompanyInfo,Contact)


# Create your views here.
def blogs(request):
    companyinfo = CompanyInfo.objects.all()[0]
    contacts = Contact.objects.all()
    # Fetch Blogs
    blogs = Blog.objects.all().order_by('-pk')
    blog_set = BlogPage.objects.all()[0]

    # pagination
    paginator = Paginator(blogs, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'blogs': page_obj,
        'companyinfo': companyinfo,
        'contacts':contacts
        }
    template_name = 'blog/blog-home.html'
    return render(request=request, template_name=template_name, context=context)


def blogDetails(request):
    companyinfo = CompanyInfo.objects.all()[0]
    contacts = Contact.objects.all()
    # Fetch Blog Details
    try:
        blog = Blog.objects.get(slug=request.GET.get('slug'))
        related = Blog.objects.filter(category=blog.category).order_by('-pk')
    except Blog.DoesNotExist:
        context = {'state': 'danger', 'message': 'Blog not found'}
        template_name = 'components/message.html'
        return render(request=request, template_name=template_name, context=context)

    
    context = {
        'blog': blog, 
        'details': markdown.markdown(blog.content_markdown), 
        'related': related[:4],
        'companyinfo':companyinfo,
        'contacts':contacts
        }
    return render(request, 'blog/blog-single.html', context=context)

def search(request):
    query = request.POST.get(key='query')
    blogs = Blog.objects.filter(
        Q(title__icontains=query) |
        Q(content_markdown__icontains=query)
    )
    blog_set = BlogPage.objects.all()[0]

    # pagination
    paginator = Paginator(blogs, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'blogs': page_obj, 'blog_set': blog_set}
    template_name = 'blog/blog-home.html'
    return render(request=request, template_name=template_name, context=context)

blog/templates/blog/blog-home.html
{% extends 'base.html' %}
<!-- Load Static -->
{% load static %}
<!-- Load Index Extras -->
{% load index_extras %}
<!-- Site Title -->
{% block title %}
<title>{{blog.title}}</title>
{% endblock title %}
<!-- Page Content -->
{% block content %}

<!-- start banner Area -->
<section class="banner-area relative blog-home-banner" id="home">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content blog-header-content col-lg-12">
        <h1 class="text-white">{{companyinfo.blog_highlight}}</h1>
        <p class="text-white">{{companyinfo.blog_description}}</p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start post-content Area -->
<section class="post-content-area">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 posts-list">
        {% if blogs %} {% for blog in blogs %}
        <div class="single-post row">
          <div class="col-lg-3 col-md-3 meta-details">
            <ul class="tags">
              <li><a href="#">{{blog.category}}</a></li>
            </ul>
            <div class="user-details row">
              <p class="user-name col-lg-12 col-md-12 col-6">
                <a href="#">{{blog.author}}</a>
                <span class="lnr lnr-user"></span>
              </p>
              <p class="date col-lg-12 col-md-12 col-6">
                <a href="#">{{blog.date_featured}}</a>
                <span class="lnr lnr-calendar-full"></span>
              </p>
            </div>
          </div>
          <div class="col-lg-9 col-md-9">
            <div class="feature-img">
              <img class="img-fluid" src="{{blog.image.url}}" alt="" />
            </div>
            <a
              class="posts-title"
              href="{% url 'blog:blog_details'%}?slug={{blog.slug}}"
              ><h3>{{blog.title}}</h3></a
            >
            <p class="excert">{{blog.brief}}</p>
            <a
              href="{% url 'blog:blog_details'%}?slug={{blog.slug}}"
              class="primary-btn"
              >View More</a
            >
          </div>
        </div>
        {% endfor %} {% else %}
        <!-- Start Sample Area -->
        <section class="sample-text-area">
          <div class="container">
            <h3 class="text-heading">No blogs Found</h3>
            <p class="sample-text">Try searching another</p>
          </div>
        </section>
        {% endif %}
        <!-- Pagination -->
        <div class="pagination col-md-6 m-auto">
          <span
            class="step-links d-flex justify-content-between p-3 border m-2 mt-3 rounded w-100"
            style="background: #fafaff"
          >
            {% if blogs.has_previous %}
            <a href="?page=1">&laquo; First</a>
            <a href="?page={{ blogs.previous_page_number }}">Previous</a>
            {% endif %}

            <span class="current">
              Page {{ blogs.number }}
              <!-- Current number -->
              of
              <!-- Total number -->
              {{ blogs.paginator.num_pages}}.
            </span>

            {% if blogs.has_next %}
            <a href="?page={{ blogs.next_page_number }}">Next</a>
            <a href="?page={{ blogs.paginator.num_pages }}">Last &raquo;</a>
            {% endif %}
          </span>
        </div>
        <!-- End of Pagination -->
      </div>
      <div class="col-lg-4 sidebar-widgets">
        <div class="widget-wrap">
          <div class="single-sidebar-widget search-widget">
            <form
              class="search-form"
              action="{% url 'blog:search'%}"
              method="post"
            >
              <!-- CSRF Token -->
              {% csrf_token %}
              <input
                placeholder="Search Posts"
                name="query"
                type="text"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Search Posts'"
              />
              <button type="submit"><i class="fa fa-search"></i></button>
            </form>
          </div>
          <div class="single-sidebar-widget ads-widget">
            <a href="#"
              ><img class="img-fluid" src="img/blog/ads-banner.jpg" alt=""
            /></a>
          </div>
          <div class="single-sidebar-widget post-category-widget">
            <h4 class="category-title">Post Catgories</h4>
            <ul class="cat-list">
              {% for category in categories %}
              <li>
                <a href="#" class="d-flex justify-content-between">
                  <p>{{category}}</p>
                  <!-- <p>37</p> -->
                </a>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End post-content Area -->

{% endblock content %}

blog/templates/blog/blog-single.html
{% extends 'base.html' %}
<!-- Load Static -->
{% load static %}
<!-- Load Index Extras -->
{% load index_extras %}
<!-- Site Title -->
{% block title %}
<title>{{blog.title}}</title>
{% endblock title %}
<!-- Page Content -->
{% block content %}

<!-- start banner Area -->
<section class="banner-area relative" id="home">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content col-lg-12">
        <h1 class="text-white">Blog Details Page</h1>
        <p class="text-white link-nav">
          <a href="/">Home </a>
          <span class="lnr lnr-arrow-right"></span
          ><a href="{% url 'blog:blogs' %}">Blog </a>
          <span class="lnr lnr-arrow-right"></span>
          <a href="#"> Blog Details Page</a>
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start post-content Area -->
<section class="post-content-area single-post-area">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 posts-list">
        <div class="single-post row">
          <div class="col-lg-12">
            <div class="feature-img">
              <img class="img-fluid" src="{{blog.image.url}}" alt="" />
            </div>
          </div>
          <div class="col-lg-3 col-md-3 meta-details">
            <ul class="tags">
              <li><a href="#">{{blog.category.name}}</a></li>
            </ul>
            <div class="user-details row">
              <p class="user-name col-lg-12 col-md-12 col-6">
                <a href="#">{{blog.author.name}}</a>
                <span class="lnr lnr-user"></span>
              </p>
              <p class="date col-lg-12 col-md-12 col-6">
                <a href="#">{{blog.date_featured}}</a>
                <span class="lnr lnr-calendar-full"></span>
              </p>
            </div>
          </div>
          <div class="col-lg-9 col-md-9">
            <a class="posts-title" href="#"><h3>{{blog.title}}</h3></a>
            <p class="excert">{{details|safe}}</p>
          </div>
        </div>
      </div>
      <div class="col-lg-4 sidebar-widgets">
        <div class="widget-wrap">
          <div class="single-sidebar-widget search-widget">
            <form
              class="search-form"
              action="{% url 'blog:search'%}"
              method="post"
            >
              <!-- CSRF Token -->
              {% csrf_token %}
              <input
                placeholder="Search Posts"
                name="query"
                type="text"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Search Posts'"
              />
              <button type="submit"><i class="fa fa-search"></i></button>
            </form>
          </div>
          <div class="single-sidebar-widget user-info-widget">
            <img src="{{blog.author.image.url}}" alt="" />
            <a href="#"><h4>{{blog.author.name}}</h4></a>
            <p>Blog writer</p>
            <ul class="social-links">
              <li>
                <a href="mailto:{{blog.author.email}}">{{blog.author.email}}</a>
              </li>
              </li>
            </ul>
            <p>
              {{blog.author.profile}}
            </p>
          </div>
          <div class="single-sidebar-widget popular-post-widget">
            <h4 class="popular-title">Similar Posts</h4>
            <div class="popular-post-list">
              {% for relative in related %}
              <!-- If not the same -->
              {% if relative.title != blog.title %}
              <div class="single-post-list d-flex flex-row align-items-center">
                <div class="thumb">
                  <img class="img-fluid" src="{{relative.image.url}}" alt="" />
                </div>
                <div class="details">
                  <a href="{% url 'blog:blog_details'%}?slug={{relative.slug}}"
                    ><h6>{{relative.title}}</h6></a
                  >
                  <p>{{relative.category.name}}</p>
                </div>
              </div>
              {% endif %} 
              <!-- End related -->
              {% endfor %}
            </div>
          </div>
          <div class="single-sidebar-widget ads-widget">
            <a href="#"
              ><img class="img-fluid" src="img/blog/ads-banner.jpg" alt=""
            /></a>
          </div>
          <div class="single-sidebar-widget post-category-widget">
            <h4 class="category-title">Post Catgory</h4>
            <ul class="cat-list">
              <li>
                <a href="#" class="d-flex justify-content-between">
                  <p>{{blog.category.name}}</p>
                  <!-- <p>37</p> -->
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End post-content Area -->
{% endblock content %}