blog/urls.py
from . import views
from django.urls import path
from .import views

app_name = 'blog'

urlpatterns = [
    path(route='', view=views.blogs, name='blogs'),
    path(route='blogs/', view=views.blogDetails, name='blog_details'),
    path(route='search/', view=views.search, name='search'), 
]

index/urls.py
from . import views
from django.urls import (path, include)

app_name = 'index'

urlpatterns = [
    path(route='', view=views.home, name='home'),
    path(route='services', view=views.services, name='services'),
    path(route='about', view=views.about, name='about'),
    path(route='contact', view=views.contact, name='contact'),
    path(route='portfolio', view=views.portfolio, name='portfolio'),
    path(route='terms-of-service', view=views.termsOfService, name='terms_of_service'),
    path(route='privacy-policy', view=views.privacyPolicy, name='privacy_policy'),
    path(route='portfolio-details/<int:id>', view=views.portfolioDetails, name='portfolio_details'),
    path(route='not-allowed', view=views.notAllowed, name='not_allowed'),
    path(route='paid-feature', view=views.paidFeature, name='paid_feature'),
    path(route='sitemap', view=views.sitemap, name='sitemap'),
    path(route='sitemap.xml', view=views.sitemap, name='sitemap'),
    path(route='robots', view=views.robots, name='robots'),
    path(route='robots', view=views.robots, name='robots'),
    path(route='ads', view=views.ads, name='ads'),
    path(route='Ads', view=views.ads, name='ads'),
    path(route='ads.txt', view=views.ads, name='ads'),
    path(route='Ads.txt', view=views.ads, name='ads'),
]

liame/urls.py
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path(route='accounts/', view=include('accounts.urls')),
    path(route='blog/', view=include('blog.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/templates/index/about.html
{% extends 'base.html' %}
<!-- Load Static -->
{% load static %}
<!-- Load Index Extras -->
{% load index_extras %}
<!-- Site Title -->
{% block title %}
<title>About</title>
{% endblock title %}
<!-- Page Content -->
{% block content %}

<!-- start banner Area -->
<section class="banner-area relative" id="home">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content col-lg-12">
        <h1 class="text-white">About Us</h1>
        <p class="text-white link-nav">
          <a href="/">Home </a>
          <span class="lnr lnr-arrow-right"></span>
          <a href="#"> About Us</a>
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start about-video Area -->
<section class="about-video-area section-gap">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 about-video-left">
        <h6 class="text-uppercase">who are we?</h6>
        <h1>{{companyinfo.about_us_highlight}}</h1>
        <p>{{companyinfo.about_us_description}}</p>
        <a class="primary-btn mt-30" href="{% url 'index:contact' %}"
          >Contact Us Now</a
        >
      </div>
      <div
        class="col-lg-6 about-video-right justify-content-center align-items-center d-flex relative"
      >
        <div class="overlay overlay-bg"></div>
        <a
          class="play-btn"
          href="https://www.youtube.com/watch?v={{companyinfo.introductory_video}}"
          ><img
            class="img-fluid mx-auto"
            src="{% static 'img/play-btn.png' %}"
            alt=""
        /></a>
      </div>
    </div>
  </div>
</section>
<!-- End about-video Area -->

<!-- Start feature Area -->
<section class="feature-area section-gap">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-md-12 pb-40 header-text text-center">
        <h1 class="pb-10 text-white">Some Features that Made us Unique</h1>
        <p class="text-white">
          Who are in extremely love with eco friendly system.
        </p>
      </div>
    </div>
    <div class="row">
      {% for feature in features %}
      <div class="col-lg-4 col-md-6">
        <div class="single-feature">
          <a href="#" class="title d-flex flex-row align-items-center">
            <span class="lnr lnr-license"></span>
            <h4>{{ feature.name }}</h4>
          </a>
          <p>{{feature.description}}</p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- End feature Area -->

<!-- Start testimonial Area -->
<section class="testimonial-area pt-120">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="menu-content pb-70 col-lg-8">
        <div class="title text-center">
          <h1 class="mb-10">Testimonial from our Clients</h1>
          <p>Who are in extremely love with eco friendly system.</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="active-testimonial-carusel">
        {% for testimonial in testimonials %}
        <div class="single-testimonial item d-flex flex-row">
          <div class="thumb">
            <img class="img-fluid" src="{{testimonial.image.url}}" alt="" />
          </div>
          <div class="desc">
            <p>{{testimonial.testimony}}</p>
            <h4 mt-30>{{testimonial.name}}</h4>
            <div class="star">
              {% for star in testimonial.rating|integer_range%}
              <span class="fa fa-star checked"></span>
              {% endfor %}
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>
<!-- End testimonial Area -->

<!-- Start callto-action Area -->
<section class="callto-action-area pt-120">
  <div class="container">
    <div class="row justify-content-center">
      <div class="callto-action-wrap col-lg-12 relative section-gap">
        <div class="content">
          <h1>{{companyinfo.quote_highlight}}</h1>
          <p class="mx-auto">{{companyinfo.quote_description}}</p>
          <a href="{% url 'index:contact' %}" class="primary-btn text-uppercase"
            >Request quote now</a
          >
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End callto-action Area -->

<!-- Start blog Area -->
<section class="blog-area section-gap">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="menu-content pb-60 col-lg-9">
        <div class="title text-center">
          <h1 class="mb-10">Ongoing Exhibitions from the scratch</h1>
          <p>Who are in extremely love with eco friendly system.</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="active-blog-carusel">
        {% for blog in blogs %}
        <div class="single-blog-post item">
          <div class="thumb">
            <img class="img-fluid" src="{{blog.image.url}}" alt="" />
          </div>
          <div class="details">
            <div class="tags">
              <ul>
                <li>
                  <a href="#">{{blog.category}}</a>
                </li>
              </ul>
            </div>
            <a href="#"><h4 class="title">{{blog.title}}</h4></a>
            <p>{{blog.brief}}</p>
            <h6 class="date">{{blog.date_featured}}</h6>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>
<!-- End blog Area -->

<!-- Start brands Area -->
<section class="brands-area pb-60 pt-60">
  <div class="container no-padding">
    <div class="brand-wrap">
      <div
        class="row align-items-center active-brand-carusel justify-content-start no-gutters"
      >
        {% for partner in partners %}
        <div class="col single-brand">
          <a href="{{partner.url}}"
            ><img class="mx-auto" src="{{partner.image.url}}" alt=""
          /></a>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>
<!-- End brands Area -->
{% endblock content %}

index/templates/index/contact.html
{% extends 'base.html' %}
<!-- Load Static -->
{% load static %}
<!-- Load Index Extras -->
{% load index_extras %}
<!-- Site Title -->
{% block title %}
<title>Contact</title>
{% endblock title %}
<!-- Page Content -->
{% block content %}
<!-- start banner Area -->
<section class="banner-area relative" id="home">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content col-lg-12">
        <h1 class="text-white">Contact Us</h1>
        <p class="text-white link-nav">
          <a href="/">Home </a>
          <span class="lnr lnr-arrow-right"></span>
          <a href="#"> Contact Us</a>
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start contact-page Area -->
<section class="contact-page-area section-gap">
  <div class="container">
    <div class="row">
      <iframe
        class="map-wrap"
        style="width: 100%; height: 445px"
        id="map"
        src="{{companyinfo.google_map}}"
        frameborder="0"
      ></iframe>
      <div class="col-lg-4 d-flex flex-column address-wrap">
        <div class="single-contact-address d-flex flex-row">
          <div class="icon">
            <span class="lnr lnr-home"></span>
          </div>
          <div class="contact-details">
            <h5>{{companyinfo.address}}</h5>
            <p>Come visit us at our home</p>
          </div>
        </div>
        <div class="single-contact-address d-flex flex-row">
          <div class="icon">
            <span class="lnr lnr-phone-handset"></span>
          </div>
          <div class="contact-details">
            <h5>{{companyinfo.telephone}}</h5>
            <p>Mon to Fri 9am to 6 pm</p>
          </div>
        </div>
        <div class="single-contact-address d-flex flex-row">
          <div class="icon">
            <span class="lnr lnr-envelope"></span>
          </div>
          <div class="contact-details">
            <h5>{{companyinfo.support_email}}</h5>
            <p>Send us your query anytime!</p>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <form
          class="form-area"
          id="contact-form"
          action="{% url 'index:contact' %}"
          method="post"
          class="contact-form text-right"
        >
          {% csrf_token %}
          <div class="row">
            <div class="col-lg-6 form-group">
              <!-- Name -->
              {{form.name}}
              <!-- name errors -->
              <p class="danger">{{form.name.error}}</p>
              <!-- email -->
              {{form.email}}
              <!-- email errors -->
              <p class="danger">{{form.email.error}}</p>
              <!-- subject -->
              {{form.subject}}
              <!-- subject errors -->
              <p class="danger">{{form.subject.error}}</p>
            </div>
            <div class="col-lg-6 form-group">
              <!-- message -->
              {{form.message}}
              <!-- message errors -->
              <p class="danger">{{form.message.error}}</p>
            </div>
            <div class="col-lg-12">
              <div class="alert-msg" style="text-align: left"></div>
              <button class="genric-btn primary circle" style="float: right">
                Send Message
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
<!-- End contact-page Area -->

{% endblock content %}

index/templates/index/home.html
{% extends 'base.html' %}
<!-- Load Static -->
{% load static %}
<!-- Load Index Extras -->
{% load index_extras %}
<!-- Site Title -->
{% block title %}
<title>Home</title>
{% endblock title %}
<!-- Page Content -->
{% block content %}
<!-- start banner Area -->
<section class="banner-area relative" id="home">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div
      class="row fullscreen d-flex justify-content-center align-items-center"
    >
      <div class="banner-content col-lg-9 col-md-12 justify-content-center">
        <h1>{{ companyinfo.home_page_highlight }}</h1>
        <p class="text-white mx-auto">
          {{ companyinfo.home_page_description }}
        </p>
        <a
          href="{% url 'index:contact' %}"
          class="primary-btn header-btn text-uppercase mt-10"
          >Contact Us Now</a
        >
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start service Area -->
<section class="service-area section-gap" id="service">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-12 pb-50 header-text text-center">
        <h1 class="mb-10">What we offer to our clients</h1>
        <p>Who are in extreme love with our eco friendly system..</p>
      </div>
    </div>
    <div class="row">
      {% for service in services %}
      <div class="col-lg-4">
        <div class="single-service">
          <a href="#"><h4>{{service.name}}</h4></a>
          <p>{{service.description}}</p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- End service Area -->

<!-- Start gallery Area -->
<section class="gallery-area pb-120">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-md-12 pb-40 header-text text-center">
        <h1 class="pb-10">Our Recent Works may impress you</h1>
        <p>Who are in extremely love with eco friendly system.</p>
      </div>
    </div>
    <div class="row">
      {% for portfolio in portfolios %}
      <div class="col-lg-6">
        <div class="single-gallery">
          <div class="content">
            <a
              href="{% url 'index:portfolio_details' portfolio.id %}"
              target="_blank"
            >
              <div class="content-overlay"></div>
              <img
                class="content-image img-fluid d-block mx-auto"
                src="{{portfolio.image.url}}"
                alt=""
              />
              <div class="content-details fadeIn-bottom">
                <h3 class="content-title mx-auto">{{portfolio.name}}</h3>
                <a
                  href="{% url 'index:portfolio_details' portfolio.id %}"
                  class="primary-btn text-uppercase mt-20"
                  >More Details</a
                >
              </div>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- End gallery Area -->

<!-- Start feature Area -->
<section class="feature-area section-gap">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-md-12 pb-40 header-text text-center">
        <h1 class="pb-10 text-white">Some Features that Made us Unique</h1>
        <p class="text-white">
          Who are in extremely love with eco friendly system.
        </p>
      </div>
    </div>
    <div class="row">
      {% for feature in features %}
      <div class="col-lg-4 col-md-6">
        <div class="single-feature">
          <a href="#" class="title d-flex flex-row align-items-center">
            <span class="lnr lnr-license"></span>
            <h4>{{ feature.name }}</h4>
          </a>
          <p>{{feature.description}}</p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- End feature Area -->

<!-- Start testimonial Area -->
<section class="testimonial-area pt-120">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="menu-content pb-70 col-lg-8">
        <div class="title text-center">
          <h1 class="mb-10">Testimonial from our Clients</h1>
          <p>Who are in extremely love with eco friendly system.</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="active-testimonial-carusel">
        {% for testimonial in testimonials %}
        <div class="single-testimonial item d-flex flex-row">
          <div class="thumb">
            <img class="img-fluid" src="{{testimonial.image.url}}" alt="" />
          </div>
          <div class="desc">
            <p>{{testimonial.testimony}}</p>
            <h4 mt-30>{{testimonial.name}}</h4>
            <div class="star">
              {% for star in testimonial.rating|integer_range%}
              <span class="fa fa-star checked"></span>
              {% endfor %}
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>
<!-- End testimonial Area -->

<!-- Start callto-action Area -->
<section class="callto-action-area pt-120">
  <div class="container">
    <div class="row justify-content-center">
      <div class="callto-action-wrap col-lg-12 relative section-gap">
        <div class="content">
          <h1>{{companyinfo.quote_highlight}}</h1>
          <p class="mx-auto">{{companyinfo.quote_description}}</p>
          <a href="{% url 'index:contact' %}" class="primary-btn text-uppercase"
            >Request quote now</a
          >
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End callto-action Area -->

<!-- Start blog Area -->
<section class="blog-area section-gap">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="menu-content pb-60 col-lg-9">
        <div class="title text-center">
          <h1 class="mb-10">Ongoing Exhibitions from the scratch</h1>
          <p>Who are in extremely love with eco friendly system.</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="active-blog-carusel">
        {% for blog in blogs %}
        <div class="single-blog-post item">
          <div class="thumb">
            <img class="img-fluid" src="{{blog.image.url}}" alt="" />
          </div>
          <div class="details">
            <div class="tags">
              <ul>
                <li>
                  <a href="#">{{blog.category}}</a>
                </li>
              </ul>
            </div>
            <a href="#"><h4 class="title">{{blog.title}}</h4></a>
            <p>{{blog.brief}}</p>
            <h6 class="date">{{blog.date_featured}}</h6>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>
<!-- End blog Area -->

<!-- Start brands Area -->
<section class="brands-area pb-60 pt-60">
  <div class="container no-padding">
    <div class="brand-wrap">
      <div
        class="row align-items-center active-brand-carusel justify-content-start no-gutters"
      >
        {% for partner in partners %}
        <div class="col single-brand">
          <a href="{{partner.url}}"
            ><img class="mx-auto" src="{{partner.image.url}}" alt=""
          /></a>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>
<!-- End brands Area -->
{% endblock content%}

index/templates/index/portfolio.html
{% extends 'base.html' %}
<!-- Load Static -->
{% load static %}
<!-- Load Index Extras -->
{% load index_extras %}
<!-- Site Title -->
{% block title %}
<title>Projects</title>
{% endblock title %}
<!-- Page Content -->
{% block content %}

<!-- start banner Area -->
<section class="banner-area relative" id="home">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content col-lg-12">
        <h1 class="text-white">Projects</h1>
        <p class="text-white link-nav">
          <a href="">Home </a>
          <span class="lnr lnr-arrow-right"></span>
          <a href="#"> Projects</a>
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start gallery Area -->
<section class="gallery-area section-gap">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-md-12 pb-40 header-text text-center">
        <h1 class="pb-10">{{companyinfo.projects_highlight}}</h1>
        <p>{{companyinfo.projects_description}}</p>
      </div>
    </div>
    <div class="row">
      {% for portfolio in portfolios %}
      <div class="col-lg-6">
        <div class="single-gallery">
          <div class="content">
            <a
              href="{% url 'index:portfolio_details' portfolio.id %}"
              target="_blank"
            >
              <div class="content-overlay"></div>
              <img
                class="content-image img-fluid d-block mx-auto"
                src="{{portfolio.image.url}}"
                alt=""
              />
              <div class="content-details fadeIn-bottom">
                <h3 class="content-title mx-auto">{{portfolio.name}}</h3>
                <a
                  href="{% url 'index:portfolio_details' portfolio.id %}"
                  class="primary-btn text-uppercase mt-20"
                  >More Details</a
                >
              </div>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- End gallery Area -->

<!-- Start brands Area -->
<section class="brands-area pb-60 pt-60">
  <div class="container no-padding">
    <div class="brand-wrap">
      <div
        class="row align-items-center active-brand-carusel justify-content-start no-gutters"
      >
        {% for partner in partners %}
        <div class="col single-brand">
          <a href="{{partner.url}}"
            ><img
              class="mx-auto"
              src="{{partner.image.url}}"
              alt="{{partner.name}}"
          /></a>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>
<!-- End brands Area -->

{% endblock content %}

index/templates/index/portfolio_details.html
{% extends 'base.html' %}
<!-- Load Index Extras -->
{% load index_extras %}
<!-- Page Title -->
{% block title %}
<title>{{portfolio.name}}</title>
{% endblock title %}
<!-- Page Content  -->
{% block content %}
<!-- start banner Area -->
<section class="banner-area relative" id="home">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content col-lg-12">
        <h1 class="text-white">Project Details</h1>
        <p class="text-white link-nav">
          <a href="{% url 'index:home' %}">Home </a>
          <span class="lnr lnr-arrow-right"></span>
          <a href="#"> Project Details</a>
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start project-details Area -->
<section class="project-details-area section-gap">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 project-details-left">
        <img class="img-fluid" src="{{portfolio.image.url}}" alt="" />
      </div>
      <div class="col-lg-6 project-details-right">
        <h3 class="pb-20">{{portfolio.name}}</h3>
        <p>{{portfolio.description}}</p>
        <div class="details-info d-flex flex-row">
          <ul class="names">
            <li>Rating</li>
            <li>Client</li>
            <li>Website</li>
            <li>Completed</li>
          </ul>
          <ul class="desc">
            <li>
              <div class="star">
                : {% for star in portfolio.rating|integer_range%}
                <span class="fa fa-star checked"></span>
                {% endfor %}
              </div>
            </li>
            <li>: {{portfolio.client}}</li>
            <li>: {{portfolio.url}}</li>
            <li>: {{portfolio.completed}}</li>
          </ul>
        </div>
        <!-- <div class="social-links mt-30">
          <a href="#"><i class="fa fa-facebook"></i></a>
          <a href="#"><i class="fa fa-twitter"></i></a>
          <a href="#"><i class="fa fa-dribbble"></i></a>
          <a href="#"><i class="fa fa-behance"></i></a>
          <a href="#"><i class="fa fa-linkedin"></i></a>
        </div> -->
      </div>
      <div class="col-lg-12 project-desc mt-60">
        <p>{{portfolio.description}}</p>
      </div>
    </div>
  </div>
</section>
<!-- End project-details Area -->

<!-- Start brands Area -->
<section class="brands-area pb-60 pt-60">
  <div class="container no-padding">
    <div class="brand-wrap">
      <div
        class="row align-items-center active-brand-carusel justify-content-start no-gutters"
      >
        {% for partner in partners %}
        <div class="col single-brand">
          <a href="{{partner.url}}"
            ><img class="mx-auto" src="{{partner.image.url}}" alt=""
          /></a>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>
<!-- End brands Area -->
{% endblock content %}

index/templates/index/services.html
{% extends 'base.html' %}
<!-- Load Static -->
{% load static %}
<!-- Load Index Extras -->
{% load index_extras %}
<!-- Site Title -->
{% block title %}
<title>Services</title>
{% endblock title %}
<!-- Page Content -->
{% block content %}
<!-- start banner Area -->
<section class="banner-area relative" id="home">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content col-lg-12">
        <h1 class="text-white">Services</h1>
        <p class="text-white link-nav">
          <a href="{% url 'index:home' %}">Home </a>
          <span class="lnr lnr-arrow-right"></span>
          <a href="{% url 'index:services' %}"> Services</a>
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start service Area -->
<section class="service-area section-gap" id="service">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-12 pb-50 header-text text-center">
        <h1 class="mb-10">{{companyinfo.services_highlight}}</h1>
        <p>{{companyinfo.services_description}}</p>
      </div>
    </div>
    <div class="row">
      {% for service in services %}
      <div class="col-lg-4">
        <div class="single-service">
          <a href="#"><h4>{{service.name}}</h4></a>
          <p>{{service.description}}</p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- End service Area -->

<!-- Start feature Area -->
<section class="feature-area section-gap">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-md-12 pb-40 header-text text-center">
        <h1 class="pb-10 text-white">Some Features that Made us Unique</h1>
        <p class="text-white">
          Who are in extremely love with eco friendly system.
        </p>
      </div>
    </div>
    <div class="row">
      {% for feature in features %}
      <div class="col-lg-4 col-md-6">
        <div class="single-feature">
          <a href="#" class="title d-flex flex-row align-items-center">
            <span class="lnr lnr-license"></span>
            <h4>{{ feature.name }}</h4>
          </a>
          <p>{{feature.description}}</p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- End feature Area -->

<!-- Start callto-action Area -->
<section class="callto-action-area section-gap">
  <div class="container">
    <div class="row justify-content-center">
      <div class="callto-action-wrap col-lg-12 relative section-gap">
        <div class="content">
          <h1>{{companyinfo.quote_highlight}}</h1>
          <p class="mx-auto">{{companyinfo.quote_description}}</p>
          <a href="#" class="primary-btn text-uppercase">Request quote now</a>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End callto-action Area -->

<!-- Start brands Area -->
<section class="brands-area pb-60 pt-60">
  <div class="container no-padding">
    <div class="brand-wrap">
      <div
        class="row align-items-center active-brand-carusel justify-content-start no-gutters"
      >
        {% for partner in partners %}
        <div class="col single-brand">
          <a href="{{partner.url}}"
            ><img class="mx-auto" src="{{partner.image.url}}" alt=""
          /></a>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>
<!-- End brands Area -->
{% endblock content%}