blog/urls.py
from . import views
from django.urls import path
from .import views

app_name = 'blog'

urlpatterns = [
    path(route='', view=views.blogs, name='blogs'),
    path(route='blogs/', view=views.blogDetails, name='blog_details'),
    path(route='search/', view=views.search, name='search'), 
]

index/urls.py
from . import views
from django.urls import (path, include)

app_name = 'index'

urlpatterns = [
    path(route='', view=views.home, name='home'),
    path(route='services', view=views.services, name='services'),
    path(route='about', view=views.about, name='about'),
    path(route='contact', view=views.contact, name='contact'),
    path(route='portfolio', view=views.portfolio, name='portfolio'),
    path(route='terms-of-service', view=views.termsOfService, name='terms_of_service'),
    path(route='privacy-policy', view=views.privacyPolicy, name='privacy_policy'),
    path(route='portfolio-details/<int:id>', view=views.portfolioDetails, name='portfolio_details'),
    path(route='not-allowed', view=views.notAllowed, name='not_allowed'),
    path(route='paid-feature', view=views.paidFeature, name='paid_feature'),
    path(route='sitemap', view=views.sitemap, name='sitemap'),
    path(route='sitemap.xml', view=views.sitemap, name='sitemap'),
    path(route='robots', view=views.robots, name='robots'),
    path(route='robots', view=views.robots, name='robots'),
    path(route='ads', view=views.ads, name='ads'),
    path(route='Ads', view=views.ads, name='ads'),
    path(route='ads.txt', view=views.ads, name='ads'),
    path(route='Ads.txt', view=views.ads, name='ads'),
]

liame/urls.py
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path(route='accounts/', view=include('accounts.urls')),
    path(route='blog/', view=include('blog.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="no-js">
  <head>
    <!-- Mobile Specific Meta -->
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Favicon-->
    <link
      rel="shortcut icon"
      href="{{companyinfo.logo.url}}"
      type="image/x-icon"
    />
    <!-- Author Meta -->
    <meta name="author" content="Juma Shafara" />
    <!-- Meta Description -->
    <meta name="description" content="" />
    <!-- Meta Keyword -->
    <meta name="keywords" content="liame, designs, liame designs, inte" />
    <!-- meta character set -->
    <meta charset="UTF-8" />
    <!-- Site Title -->
    {% block title %}
    <title>Liame Desgins</title>
    {% endblock title %}

    <link
      href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700"
      rel="stylesheet"
    />
    <!--
        CSS
        ============================================= -->
    <link rel="stylesheet" href="{% static 'css/linearicons.css' %} " />
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %} " />
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %} " />
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %} " />
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %} " />
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %} " />
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %} " />
    <link rel="stylesheet" href="{% static 'css/main.css' %} " />
  </head>
  <body>
    <header id="header" id="home">
      <div class="header-top">
        <div class="container">
          <div class="row">
            <div class="col-lg-6 col-sm-6 col-4 header-top-left no-padding">
              <a href="tel:{{companyinfo.telephone}}"
                >{{companyinfo.telephone}}</a
              >
              <a href="mailto:{{companyinfo.support_email}}"
                >{{companyinfo.support_email}}</a
              >
            </div>
            <div class="col-lg-6 col-sm-6 col-8 header-top-right no-padding">
              <ul>
                {% for contact in contacts %}
                <li>
                  <a href="{{contact.contact}}" target="_blank"
                    ><i class="{{contact.icon}}"></i
                  ></a>
                </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="container main-menu">
        <div class="row align-items-center justify-content-between d-flex">
          <div id="logo">
            <a href="/"
              ><img src="{{companyinfo.logo.url}}" alt="" title=""
            /></a>
          </div>
          <nav id="nav-menu-container">
            <ul class="nav-menu">
              <li class="menu-active"><a href="/">Home</a></li>
              <li><a href="{% url 'index:about' %}">About</a></li>
              <li><a href="{% url 'index:services' %}">Services</a></li>
              <li><a href="{% url 'index:portfolio' %}">Projects</a></li>
              <li class="">
                <a href="{% url 'blog:blogs' %}">Blog</a>
              </li>
              <li><a href="{% url 'index:contact' %}">Contact</a></li>
              <li><a href="/admin" target="_blank">Administer</a></li>
            </ul>
          </nav>
          <!-- #nav-menu-container -->
        </div>
      </div>
    </header>
    <!-- #header -->

    {% block content %}
    <!-- Content Goes Here -->
    {% endblock content%}

    <!-- start footer Area -->
    <footer class="footer-area section-gap">
      <div class="container">
        <div class="row">
          <div class="col-lg-5 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>About Us</h6>
              <p>{{companyinfo.about_us_description}}</p>
              <p class="footer-text">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;
                <script>
                  document.write(new Date().getFullYear());
                </script>
                All rights reserved | Designed with
                <i class="fa fa-heart-o" aria-hidden="true"></i> by
                <a href="https://jumashafara.dataidea.com" target="_blank"
                  >Juma Shafara</a
                >
                and distributed by
                <a href="https://www.dataidea.com/" target="_blank">DATAIDEA</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              </p>
            </div>
          </div>
          <div class="col-lg-5 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>Newsletter</h6>
              <p>Stay update with our latest</p>
              <div class="" id="mc_embed_signup">
                <form
                  target="_blank"
                  novalidate="true"
                  action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                  method="get"
                  class="form-inline"
                >
                  <input
                    class="form-control"
                    name="EMAIL"
                    placeholder="Email Address"
                    onfocus="this.placeholder = ''"
                    onblur="this.placeholder = 'Email Address'"
                    required=""
                    type="email"
                  />
                  <button class="click-btn btn btn-default">
                    <i class="lnr lnr-arrow-right" aria-hidden="true"></i>
                  </button>
                  <div style="position: absolute; left: -5000px">
                    <input
                      name="b_36c4fd991d266f23781ded980_aefe40901a"
                      tabindex="-1"
                      value=""
                      type="text"
                    />
                  </div>
                  <div class="info"></div>
                </form>
              </div>
            </div>
          </div>
          <div class="col-lg-2 col-md-6 col-sm-6 social-widget">
            <div class="single-footer-widget">
              <h6>Follow Us</h6>
              <p>Let us be social</p>
              <div class="footer-social d-flex align-items-center">
                {% for contact in contacts %}
                <a href="{{contact.contact}}" target="_blank"
                  ><i class="{{contact.icon}}"></i
                ></a>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- End footer Area -->

    <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <script
      type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"
    ></script>
    <script src="{% static 'js/easing.min.js' %}"></script>
    <script src="{% static 'js/hoverIntent.js' %}"></script>
    <script src="{% static 'js/superfish.min.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

templates/message.html
{% extends 'base.html' %}
<!-- Load Static -->
{% load static %}
<!-- Load Index Extras -->
{% load index_extras %}
<!-- Site Title -->
{% block title %}
<title>About</title>
{% endblock title %}
<!-- Page Content -->
{% block content %}
<!-- start banner Area -->
<section class="banner-area relative" id="home">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content col-lg-12">
        <h1 class="text-white">Message</h1>
        <p class="text-white link-nav">
          <a href="/">Home </a>
          <span class="lnr lnr-arrow-right"></span>
          <a href="#"> Message</a>
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->
<!-- Start Sample Area -->
<section class="sample-text-area">
  <div class="container">
    <h3 class="text-heading">Hello there...</h3>
    <p class="sample-text">{{message}}</p>
  </div>
</section>
<!-- Start contact-page Area -->
<section class="contact-page-area section-gap">
  <div class="container">
    <div class="row">
      <iframe
        class="map-wrap"
        style="width: 100%; height: 445px"
        id="map"
        src="{{companyinfo.google_map}}"
        frameborder="0"
      ></iframe>
      <div class="col-lg-4 d-flex flex-column address-wrap">
        <div class="single-contact-address d-flex flex-row">
          <div class="icon">
            <span class="lnr lnr-home"></span>
          </div>
          <div class="contact-details">
            <h5>{{companyinfo.address}}</h5>
            <p>Come visit us at our home</p>
          </div>
        </div>
        <div class="single-contact-address d-flex flex-row">
          <div class="icon">
            <span class="lnr lnr-phone-handset"></span>
          </div>
          <div class="contact-details">
            <h5>{{companyinfo.telephone}}</h5>
            <p>Mon to Fri 9am to 6 pm</p>
          </div>
        </div>
        <div class="single-contact-address d-flex flex-row">
          <div class="icon">
            <span class="lnr lnr-envelope"></span>
          </div>
          <div class="contact-details">
            <h5>{{companyinfo.support_email}}</h5>
            <p>Send us your query anytime!</p>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <form
          class="form-area"
          id="myForm"
          action="{% url 'index:contact' %}"
          method="post"
          class="contact-form text-right"
        >
          {% csrf_token %}
          <div class="row">
            <div class="col-lg-6 form-group">
              <!-- Name -->
              {{form.name}}
              <!-- name errors -->
              <p class="danger">{{form.name.error}}</p>
              <!-- email -->
              {{form.email}}
              <!-- email errors -->
              <p class="danger">{{form.email.error}}</p>
              <!-- subject -->
              {{form.subject}}
              <!-- subject errors -->
              <p class="danger">{{form.subject.error}}</p>
            </div>
            <div class="col-lg-6 form-group">
              <!-- message -->
              {{form.message}}
              <!-- message errors -->
              <p class="danger">{{form.message.error}}</p>
            </div>
            <div class="col-lg-12">
              <div class="alert-msg" style="text-align: left"></div>
              <button class="genric-btn primary circle" style="float: right">
                Send Message
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
<!-- End contact-page Area -->

{% endblock content %}